dist: xenial
language: python
python: 3.7
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
install: pip install tox
script:
- |
  if [[ $TRAVIS_TAG == "" ]]; then
    tox
  fi
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: yeFCKeHV7ekqfwcU3j8Ea8TO8qA3E9mIlbz9cIyU6QcvMyQUWFM3kPECJBKqYBwvuATvps6QmozExSpQXwUda6K+IHN7G6dJApl4AJijo3Le8JAtbEik1HX3lGiOtP2JmhZRLn4a+Ms2qAlGBWiq8wF2VNhlSQ2pGOlydq8MpRnMDpBZAbuLPN3oLoxuu77lQtoTe7lWN8yXe8hu4O0FuYcUpxGb3HmNZfeANYnANOJaijxI0xO9oM51uUTSXT1PO5ZTJKnaJQLmlwWC49R2Ct0hHEWYOzungZejiADI8A5MKLNiX7iPWVIMXbwnV39TNJtKRJvTuRSCp73xoHrXYIViImURXdYIrOkTUOIo3pVGmRPZ0SRBBqwpSWTPmDKfEV/iTtP97EqIJL+xurdsJ7YXfktq4y3ugY0SO/uUI7nGZg+uWEpTj657BT4LQ9Wt+ubibvF0rw6oKMSo+2veQel+qcrw8hSvsvqdb47UooLf0bMOQVoWfU27YkbYbg/lqsnuJ2UezLUbFkWIHkU7fXWyumpqdWe/IUYW7nO/14PM32DCMoincGmraBfN+/m3azU0qgoQfbnW94r1KRM8B2g4ZCCAmJYI4z9WK0qUYCTDs0Gtr5llV4WlHcIDXrDfxahqASDzw0QijHpfRXFVMBBZ13MhdNzvVuESyQlOueM=
  skip_cleanup: true
  on:
    tags: true
