name: Build
on:
  - push
  - pull_request
jobs:
  test:
    if: github.repository == 'adobe/pydc-control'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.7
        - 3.8
        - 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: Test with pycodestyle
      run: pycodestyle pydc_control
    - name: Test with pylint
      run: pylint pydc_control
    - name: Test with pytest
      run: pytest --junitxml=test-reports/test-results.xml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: test-reports/test-results.xml
        check_name: "Test Results ${{ matrix.python-version }}"
  publish:
    if: github.repository == 'adobe/pydc-control'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch all history in order to get the commit count for the version in setup.py
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Remove version file
      # This is just in case something else created it, destroy it so we'll get a fresh version
      run: rm -f pydc_control/VERSION
    - name: Install wheel
      run: pip install wheel
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Check upload
      run: pip install twine && twine check dist/*
    - name: Publish to PyPi
      # Only publish if this was a push
      if: github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.ADOBE_BOT_PYPI_TOKEN }}
